[0m01:02:29.833263 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77bcebf65a80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77bcea8272e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77bcea8269b0>]}


============================== 01:02:29.857077 | a6ff22d0-f6dd-4034-ab31-953b2b9cd10e ==============================
[0m01:02:29.857077 [info ] [MainThread]: Running with dbt=1.8.2
[0m01:02:29.857869 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:02:29.858665 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-drefeeney/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:02:29.861666 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.07751406, "process_user_time": 1.162427, "process_kernel_time": 0.221414, "process_mem_max_rss": "85140", "process_in_blocks": "68872", "process_out_blocks": "8", "command_success": false}
[0m01:02:29.862674 [debug] [MainThread]: Command `dbt run` failed at 01:02:29.862523 after 0.08 seconds
[0m01:02:29.863354 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77bcebf65a80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77bcea827640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77bcea827cd0>]}
[0m01:02:29.864007 [debug] [MainThread]: Flushing usage events
[0m11:56:34.221514 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7280b3fc5ae0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7280b287eaa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7280b287fdf0>]}


============================== 11:56:34.243951 | 4dd4fea8-ff1d-459a-8ff0-5a4c990b1b24 ==============================
[0m11:56:34.243951 [info ] [MainThread]: Running with dbt=1.8.2
[0m11:56:34.245397 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/vscode/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:56:34.246143 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-drefeeney/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:56:34.247378 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.08104898, "process_user_time": 1.350294, "process_kernel_time": 0.284272, "process_mem_max_rss": "85468", "process_in_blocks": "68896", "process_out_blocks": "8", "command_success": false}
[0m11:56:34.248090 [debug] [MainThread]: Command `dbt run` failed at 11:56:34.247982 after 0.08 seconds
[0m11:56:34.248569 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7280b3fc5ae0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7280b287f490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7280b287feb0>]}
[0m11:56:34.249054 [debug] [MainThread]: Flushing usage events
[0m12:08:23.714156 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79970aec9b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79970973fee0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79970973e170>]}


============================== 12:08:23.718511 | cec476ec-276d-41bc-a557-7ae827ff092f ==============================
[0m12:08:23.718511 [info ] [MainThread]: Running with dbt=1.8.2
[0m12:08:23.719283 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:08:23.719886 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-drefeeney/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:08:23.720871 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.05851693, "process_user_time": 1.225259, "process_kernel_time": 0.110668, "process_mem_max_rss": "85500", "process_in_blocks": "4024", "process_out_blocks": "8", "command_success": false}
[0m12:08:23.721510 [debug] [MainThread]: Command `dbt run` failed at 12:08:23.721402 after 0.06 seconds
[0m12:08:23.721960 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79970aec9b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x799709be21d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x799709be3640>]}
[0m12:08:23.722402 [debug] [MainThread]: Flushing usage events
